# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AirMap' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for AirMap
  
pod 'GoogleMaps', '1.13.2'
pod 'AFNetworking', '3.1.0'
pod 'SDWebImage', '3.8.1'
pod 'Realm', '1.0.1'
end
